# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
